### ISSUE TITLE
Put attribution and OSS licence blurb into readme.md

### ISSUE THREAD

**Issue by ounsworth** [FRC2706/2018-2706-Robot-Code#2]
See the discussion on this wiki page:
https://github.com/FRC2706/2018-2706-Robot-Code/wiki/Draft-attribution-blurb-for-2706-code

**Comment by ounsworth** [comment]
BUMP! Hey @eandr127 @Vanilla-Rain @jogray72 @greyingjay Can someone stick the attribution blurb linked above into your `readme.md`, and add an MIT license to the repo ?

**Comment by eandr127** [comment]
@ounsworth I made a pull request with the license changes. Would you be able to take a look and make sure that they're what you want?
